// Phase 3A: the generic payment-provider abstraction. No handler/route calls any of this yet
// (this phase is DB/domain foundation only, per the brief) — it exists so a later phase can add
// PhonePePaymentProvider (see phonepe-payment-provider.ts's stub) without touching
// create-payment-attempt.ts/confirm-successful-payment.ts/sync-payment-status.ts, which only ever
// talk to this interface, never to a specific provider's SDK/HTTP API directly.
//
// Deliberately provider-agnostic: no field here is PhonePe-specific (no merchantId, no
// X-VERIFY/checksum header, no PhonePe response envelope shape). Real PhonePe request/response
// wiring — including how it signs and verifies requests — is intentionally not guessed at in this
// phase; see phonepe-payment-provider.ts's header for why.

import type { PaymentProvider } from './payment-repository';

/** What a provider call reports about a payment attempt, collapsed to the three outcomes the
 *  rest of this codebase's domain logic actually branches on (see sync-payment-status.ts).
 *  'PENDING' covers every provider-side "not resolved yet" state (initiated, awaiting the
 *  customer, awaiting bank confirmation, etc.) — this phase has no need to distinguish those
 *  finer-grained states since none of them changes what confirm-successful-payment.ts or
 *  sync-payment-status.ts do. */
export type ProviderOutcome = 'SUCCESS' | 'FAILED' | 'PENDING';

export interface CreatePaymentRequest {
  /** Our own merchant-side reference for this attempt (payments.provider_order_id) — generated by
   *  create-payment-attempt.ts before this is called, never by the provider. */
  providerOrderId: string;
  amountInr: number;
  currency: string;
  /** A short line for the provider's own dashboard/receipt (e.g. the Xperience name) — never data
   *  the confirmation logic depends on. */
  description: string;
}

export interface CreatePaymentResult {
  /** Where the customer completes payment (a hosted checkout page), when the provider works that
   *  way. Optional because a provider/mode that doesn't redirect (e.g. this phase's mock) has
   *  nothing to put here. */
  redirectUrl?: string;
  /** The provider's raw create-order response, kept only for audit/debugging (payments.metadata)
   *  — never read back for a business decision. */
  raw?: unknown;
}

export interface ProviderStatusResult {
  outcome: ProviderOutcome;
  /** Only meaningful when outcome is 'SUCCESS' — the provider's own transaction id. */
  providerTransactionId?: string;
  /** The amount/currency the *provider* reports as paid — this is exactly the untrusted input
   *  confirm-successful-payment.ts checks against the server-controlled payments.amount_inr/
   *  currency before ever marking anything paid; it is never assumed correct on its own. */
  amountInr?: number;
  currency?: string;
  /** Only meaningful when outcome is 'FAILED'. */
  failureReason?: string;
  raw?: unknown;
}

/** The result of independently verifying an inbound webhook/callback body (signature, origin,
 *  well-formedness) — shaped like ProviderStatusResult plus the provider_order_id the payload
 *  claims to be about, since a webhook (unlike a status poll) doesn't already know which payment
 *  it's talking about until the payload is parsed and trusted. Returns null when the payload
 *  fails verification (bad/missing signature, malformed body) — the caller must treat that as "no
 *  information", never as a FAILED outcome. */
export interface WebhookVerificationResult extends ProviderStatusResult {
  providerOrderId: string;
}

export interface RefundRequest {
  providerOrderId: string;
  providerTransactionId: string;
  amountInr: number;
  reason: string;
}

export interface RefundResult {
  providerRefundId: string;
  raw?: unknown;
}

/**
 * Everything the payment domain layer needs from a payment gateway, independent of which one.
 * confirm-successful-payment.ts/create-payment-attempt.ts/sync-payment-status.ts depend only on
 * this interface — see this file's header.
 */
export interface PaymentProviderAdapter {
  readonly provider: PaymentProvider;

  /** Starts a new payment attempt with the provider for an already-created `payments` row (see
   *  create-payment-attempt.ts) — never called with browser-supplied amount/currency, always the
   *  values create-payment-attempt.ts itself derived from the booking's server-side price. */
  createPayment(request: CreatePaymentRequest): Promise<CreatePaymentResult>;

  /** Polls the provider for an attempt's current outcome, keyed by our own provider_order_id —
   *  used by sync-payment-status.ts as a fallback/reconciliation path alongside (not instead of)
   *  webhook delivery. */
  getPaymentStatus(providerOrderId: string): Promise<ProviderStatusResult>;

  /** Verifies an inbound webhook/callback body actually came from this provider (signature/origin
   *  check) and extracts its outcome — returns null if verification fails. This is where a real
   *  provider's signature-checking logic belongs; see phonepe-payment-provider.ts's stub for why
   *  PhonePe's isn't implemented yet. */
  verifyWebhook(payload: string, headers: Record<string, string | undefined>): Promise<WebhookVerificationResult | null>;

  /** Reserved for a future phase — no caller invokes this yet (Phase 3A has no refund flow). */
  refundPayment(request: RefundRequest): Promise<RefundResult>;
}
