-- Phase 3A: payment and booking-lifecycle foundation.
--
-- Applied by the migration Lambda (infra/lib/lambda/migrate/handler.ts), same mechanism as
-- 001_initial_schema.sql/002_simulator_inventory.sql — never automatically, never on deploy, see
-- infra/lib/constructs/migration.ts. Run inside its own transaction by the migration runner; if
-- anything below fails, none of it applies (and 001's/002's tables/data are untouched either way).
--
-- Purely additive: no ALTER/DROP touches `products`, `bookings`, `simulators`, or
-- `booking_allocations` — this migration adds one new table (`payments`) and one new enum
-- (`payment_status`). No existing row is modified or deleted.
--
-- Backward compatibility decision (see this repo's CLAUDE.md and the Phase 3A brief): bookings.
-- status already has a 'confirmed' value in 001's booking_status enum — defined then but never
-- written by any handler (create-booking.ts only ever inserts 'pending'). A successful payment
-- transitions a booking from 'pending' to that already-existing 'confirmed' value (see
-- backend/src/lib/confirm-successful-payment.ts) — booking_status itself needs no change at all.
-- allocation_status likewise already has the 'confirmed' value this phase needs (defined in 002,
-- never written yet either) — a successful payment moves a booking's HOLD allocation rows to
-- 'confirmed' and clears hold_expires_at, exactly the transition 002's header already reserved
-- that value for. Nothing here redefines or renames any existing enum value.
--
-- Out of scope by design (see the Phase 3A brief): no admin UI, no real PhonePe network calls, no
-- webhook API route/infrastructure — this migration only prepares the data model a later phase's
-- webhook handler will write to via backend/src/lib/confirm-successful-payment.ts.

-- ============================================================================
-- Enums
-- ============================================================================

-- Lifecycle of one payment attempt (one `payments` row). A booking may accumulate several rows
-- over time (a failed/expired attempt followed by a successful one) — see the payments table
-- comment below for why that's safe.
--   'created'  — a payment attempt has been recorded and (in a future phase) handed to the
--                provider to start a checkout, but the provider hasn't reported anything back yet.
--   'pending'  — the provider has acknowledged the attempt and is waiting on the customer/bank
--                (e.g. redirected to complete payment) — reserved for a future phase; nothing
--                writes this value yet.
--   'paid'     — verified successful payment. See confirm-successful-payment.ts: this is the only
--                state transition that also confirms the related booking/allocations.
--   'failed'   — the provider reported the attempt did not succeed. Terminal: never transitions to
--                'paid' (a genuinely new attempt is a new `payments` row, not a status flip).
--   'expired'  — the attempt's payment window lapsed with no outcome from the provider. Terminal,
--                same rationale as 'failed'.
--   'refunded' — a previously 'paid' payment was refunded. Reserved for a future phase; nothing
--                writes this value yet.
CREATE TYPE payment_status AS ENUM ('created', 'pending', 'paid', 'failed', 'expired', 'refunded');

-- Which payment gateway processed the attempt. 'mock' exists only for automated tests (see
-- backend/src/lib/mock-payment-provider.ts) and must never appear on a real attempt; 'phonepe' is
-- the only real provider planned, and its actual API integration is a later phase (see
-- backend/src/lib/phonepe-payment-provider.ts's stub — Phase 3A doesn't have PhonePe credentials
-- or final API docs yet).
CREATE TYPE payment_provider AS ENUM ('phonepe', 'mock');

-- ============================================================================
-- payments — one row per payment attempt against a booking. A booking has zero or more of these;
-- see the uniqueness/partial-index rules below for how "one booking, many attempts, at most one
-- successful outcome" is enforced.
-- ============================================================================

CREATE TABLE payments (
  id                        UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- ON DELETE RESTRICT, matching products.id -> bookings' rationale (001): a financial record must
  -- never be deleted out from under a booking. Nothing in this codebase deletes a booking anyway.
  booking_id                UUID NOT NULL REFERENCES bookings (id) ON DELETE RESTRICT,

  provider                  payment_provider NOT NULL,

  -- The merchant-side reference for this attempt: generated by our own backend (crypto.randomUUID()
  -- — see create-payment-attempt.ts) at attempt-creation time and handed to the provider as the
  -- order/merchant-transaction id when a future phase actually calls it. This is what a provider
  -- webhook/callback carries back and is looked up by — see confirm-successful-payment.ts, which
  -- locks a payment row by (provider, provider_order_id), never by guessing booking_id from the
  -- callback body.
  provider_order_id         TEXT NOT NULL,

  -- The provider's own transaction id for a *successful* attempt — assigned by the provider, only
  -- known once payment succeeds, so NULL until then. Never used to look up a payment (that's
  -- provider_order_id's job); recorded so a successful attempt has an audit trail back to the
  -- provider's own records, and so the same provider transaction id can never be attached to two
  -- different payments rows (see the partial unique index below).
  provider_transaction_id   TEXT,

  -- What this attempt is for: a snapshot of the booking's price at attempt-creation time (from
  -- bookings.price_inr, itself already a snapshot of the product's price — see 001), not a live
  -- lookup of the product's *current* price. This is the "server-controlled expected amount" a
  -- provider-reported paid amount is checked against in confirm-successful-payment.ts — the
  -- browser never supplies this value at any point in the flow.
  amount_inr                NUMERIC(10, 2) NOT NULL CHECK (amount_inr >= 0),

  -- Play X only operates in India / INR today (see CLAUDE.md's pricing/product-catalog notes) —
  -- constrained to the one supported value rather than left open, so a currency mismatch is a
  -- schema-level impossibility, not just an application-level check. Loosen this (and the
  -- application-level currency comparison in confirm-successful-payment.ts) in a later migration
  -- if Play X ever needs a second currency.
  currency                  TEXT NOT NULL DEFAULT 'INR' CHECK (currency = 'INR'),

  payment_status            payment_status NOT NULL DEFAULT 'created',

  failure_reason            TEXT,

  -- Raw provider payload/notes for audit and debugging (e.g. the provider's create-order response,
  -- or the verified webhook body) — never read back for business-logic decisions; every field that
  -- actually drives a decision (amount, currency, transaction id, outcome) has its own typed
  -- column above. Nullable: most rows never need it.
  metadata                  JSONB,

  created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- NULL until the attempt is verified successful; see confirm-successful-payment.ts, the only
  -- writer of 'paid'/paid_at.
  paid_at                   TIMESTAMPTZ,

  -- A 'paid' attempt always has paid_at set...
  CONSTRAINT payments_paid_requires_paid_at_chk CHECK (payment_status <> 'paid' OR paid_at IS NOT NULL),
  -- ...and none of the states that precede or replace a successful payment ever carry one. Not
  -- applied to 'refunded': a refund happens *after* a payment was paid, so paid_at legitimately
  -- stays set through that transition (a future refund phase decides whether it clears it).
  CONSTRAINT payments_unpaid_has_no_paid_at_chk
    CHECK (payment_status NOT IN ('created', 'pending', 'failed', 'expired') OR paid_at IS NULL)
);

-- Every attempt against a booking, most recent first — the common "this booking's payment
-- history" query, and what confirm-successful-payment.ts's "is there already another paid
-- attempt?" check filters on.
CREATE INDEX idx_payments_booking_id ON payments (booking_id);

CREATE INDEX idx_payments_status ON payments (payment_status);

-- Provider order ids are generated by us (see provider_order_id's comment) and handed to exactly
-- one provider per attempt, so global uniqueness within a provider is the right scope — the
-- lookup confirm-successful-payment.ts does (by provider, provider_order_id) relies on this being
-- unique so "identify and lock the payment record" is always exactly one row.
CREATE UNIQUE INDEX idx_payments_provider_order_id_unique ON payments (provider, provider_order_id);

-- A provider transaction id is only meaningful once an attempt succeeds (see the column comment)
-- and, when present, must never be shared by two different payments rows — this is the DB-level
-- backstop behind "duplicate provider transaction is protected" (see confirm-successful-payment.ts
-- and its tests): even if application logic were bypassed, Postgres itself refuses to attach the
-- same real-world transaction to two attempts. Partial (WHERE ... IS NOT NULL) so the many rows
-- that never reach a successful outcome don't collide on a shared NULL.
CREATE UNIQUE INDEX idx_payments_provider_transaction_id_unique
  ON payments (provider, provider_transaction_id)
  WHERE provider_transaction_id IS NOT NULL;

-- The core "one successful payment must not produce multiple booking confirmations" guarantee
-- (see the Phase 3A brief): at most one 'paid' row per booking, enforced by Postgres itself rather
-- than only by application logic. A booking can still accumulate any number of 'created'/
-- 'pending'/'failed'/'expired' rows (retries) — this index only ever constrains the 'paid' ones.
CREATE UNIQUE INDEX idx_payments_one_paid_per_booking ON payments (booking_id) WHERE payment_status = 'paid';

CREATE TRIGGER payments_set_updated_at
  BEFORE UPDATE ON payments
  -- set_updated_at() already exists — defined by 001_initial_schema.sql, reused as-is.
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
